## H2 Connection
spring:
  datasource:
    url: jdbc:h2:mem:desafiodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Client
  h2:
    console:
      enabled: true
      path: /h2-console

  #Show SQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

